send_trajectory:
  ros__parameters:
    gait:
      total_gait_time: 1.0
      step_length: 0.01
      swing_height: 0.01
      trajectory_points: 100

    default_stance:
      FL:
        coxa: 0.785398
        femur: 0.785398
        tibia: 2.53073
      FR:
        coxa: 2.35619
        femur: 0.785398
        tibia: 2.53073
      BL:
        coxa: 0.785398
        femur: 0.785398
        tibia: 2.53073
      BR:
        coxa: 2.35619
        femur: 0.785398
        tibia: 2.53073
